/// <reference types="cypress" />
describe('DashBoard', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('Shall Post/Comment CRUD works fine', () => {
    cy.get('input[placeholder="Email"]').type('user1@user1.jp')
    cy.get('input[placeholder="Password"]').type('password123')
    cy.get("[type='submit']").click()
    cy.get('[data-testid="logout"]').should('be.visible')
    cy.get('input[placeholder="New post ?"]').type('Post A')
    cy.get('[data-testid="btn-post"]').click()
    cy.get('[data-testid="ul-post"]').children().should('have.length', 1)
    cy.get('[data-testid="ul-post"]').children().should('have.text', 'Post A')
    cy.get('[data-testid="pencil-post"]').click()
    cy.get('input[placeholder="New post ?"]').type('++')
    cy.get('[data-testid="btn-post"]').click()
    cy.get('[data-testid="ul-post"]').children().should('have.text', 'Post A++')
    cy.get('[data-testid="open-comments"]').click()
    cy.get('input[placeholder="New comment ?"]').should('be.visible')
    cy.get('input[placeholder="New comment ?"]').type('Comment A')
    cy.get('[data-testid="btn-comment"]').click()
    cy.get('[data-testid="ul-comment"]').children().should('have.length', 1)
    cy.get('[data-testid="pencil-comment"]').click()
    cy.get('input[placeholder="New comment ?"]').type('++')
    cy.get('[data-testid="btn-comment"]').click()
    cy.get('[data-testid="ul-comment"]')
      .children()
      .should('have.text', 'Comment A++')
    cy.get('[data-testid="trash-post"]').click()
    cy.get('[data-testid="ul-comment"]').children().should('have.length', 0)
    cy.get('[data-testid="ul-post"]').children().should('have.length', 0)
  })
})
export {}
